; PlatformIO Project Configuration File
; Landslide Early Warning System (EWS)
; Board : DFRobot FireBeetle ESP32 IoT Microcontroller
; Sensors: GY-LSM6DS3, DFRobot Piezo Vibration Sensor
; Output : Relay → Mini Siren Strobo 12V, LED Status, LCD I2C

[env]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 460800
upload_resetmethod = nodemcu
monitor_speed = 115200

; Libraries
lib_deps =
    ; LSM6DS3 IMU (Accelerometer + Gyroscope)
    sparkfun/SparkFun LSM6DS3 Breakout@^1.0.3
    adafruit/Adafruit LSM6DS@^4.7.4
    adafruit/Adafruit Unified Sensor@^1.1.14
    adafruit/Adafruit BusIO@^1.16.2
    ; GPS parsing
    mikalhart/TinyGPSPlus@^1.0.3
    ; LCD I2C 16x2
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    ; WiFi & MQTT for IoT monitoring
    knolleary/PubSubClient@^2.8
    ; ArduinoJson for data formatting
    bblanchon/ArduinoJson@^7.3.1

; Build flags
build_flags =
    -D ARDUINO_ESP32_DEV
    -D CORE_DEBUG_LEVEL=0

[env:esp32dev]
build_src_filter = +<main.cpp>

[env:esp32dev-gps-test]
build_src_filter = +<gps_test.cpp>

[env:esp32dev-gps-test-v2]
build_src_filter = +<gps_test_v2.cpp>
